import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to FdotDaily</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Script src="/sc.js" strategy="lazyOnload"> </Script> */}

    <nav className={styles.mainnav}>
      <ul>
        <li>Home</li>
        <li>About</li>
        <li>Blog</li>
        <li>Contact</li>
      </ul>
    </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Fdot Daily
        </h1>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
      <div className="blogs">
        <div className="blogItem">
          <h2>Popular Blogs</h2>
          <h3>How to learn JavaScript in 2022</h3>
          <p>Javascipt is language on client side.</p>
          <h3>How to learn JavaScript in 2022</h3>
          <p>Javascipt is language on client side.</p>
          <h3>How to learn JavaScript in 2022</h3>
          <p>Javascipt is language on client side.</p>
        </div>
      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
